### ISSUE TITLE
Changing schedule that runs once a month causes healthCheck to trigger

### ISSUE THREAD

**Issue by DagBertelsen** [storebrand/scheduledtask#25]
If you have a schedule running once a month:
0 15 14 2-8 * ?

Let this schedule run, wait a couple of days to when it is "not running" and then change the schedule to 
0 20 14 2-8 * ?

This will cause a healthCheck to trigger. Due to the healthCheck is calculating the next run from  run logs _Run start_ time + active cron schedule it will calculate it should have ran 5 min after the last run.

IE: Last run where 2024-02-08T14:15:00.005342
changing the schdule 2024-02-12 to running at 14:20 instead. Then the healthCheck will expect the last run where triggered
2024-02-08T14:20:00.005342

To manually fix this either update the last run in the table or retrigger a new run and thus creating a new run log.

**Comment by stolsvik** [comment]
So, the issue is changing a schedule from e.g. once a month, to a schedule that runs once an hour - in the programmatic schedule, e.g. defined in the @SchedluledTask annotation.

Due to the actual calculated next run sitting in the database, this change won't effected until the next "once per month" run. That is, the code for reevaluating the cron schedule will is not run until after the next run..! So a manual solution that is employed is to hit the "Run now" button, which then obviously forces a run, and then uses the new schedule.

A solution could be to re/evaluate all the "next run" database entries upon start. The active node could do this - i.e. have a flag `justStarted = true`, and when entering the active node situation  (i.e. the single node that does this), it would eavluate this flag, do "house keeping duties", and then set it to false.

"House keeping" could encompass doing this reevaluation of all "next run" entries in the DB, and also clear out all logs from tasks that are not defined anymore.

We really only want to reevaluate those that have actually changed their cron schdule in the Java code. This due to a situation were you go from e.g. "every Monday at 00:00" to "every day at 23:00". If we now redeploy this service, with this new schedule, on e.g. Wednesday at 18:00, and we do reevaluatio against the "last run" datapoint, we would get into a situation where this task was massively overdue (It should have run Monday 23:00), and would run immediately. This would proably come unexpected on the developers would have expected it to run at Wednesday at 23.

So, if we only reevaluate the ones that actually have changed schedule, we'd rather evaluate against "now", and find that the next run should be Wednesday at 23.

But we have an issue with how know that the schedule defined in Java code have changed - that change resides in git, not in our DB data structures!

So, how can we get it into the DB structure?

There's a text field for each task defining any cron override. This is currently NULL when there is no override (i.e. the scheduled defined in the Java code is employed), and set to the override schedule if overridden.

A solution could be to always use this field to also store the original schedule if NOT overriden. Might be a tad dirty.

The other solution is to migrate the DB to include a column holding the "original schedule", so that this could be compared the the current - and if different, do the reevaulation of next rn (and re-set the "original schedule" to new), if not different, then not do it.
